name: frame_progressive_sprite_viewer
description: "Basic image and sprite viewer for Brilliant Labs Frame allowing for progressive rendering"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  frame_msg: ^2.0.0
  image: ^4.3.0
  logging: ^1.2.0
  simple_frame_app: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - packages/frame_msg/lua/battery.min.lua
    - packages/frame_msg/lua/code.min.lua
    - packages/frame_msg/lua/data.min.lua
    - packages/frame_msg/lua/image_sprite_block.min.lua
    - assets/frame_app.min.lua
